[build]
  base = "/"
  TZ = "Europe/Berlin"

[functions]
  directory = "functions"

[functions."willhaben-database-scheduled"]
  schedule = "15 * * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200