[build]
  base = "/"
  TZ = "Europe/Berlin"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[functions."willhaben-database-scheduled"]
  schedule = "5/5 7 * * *"

[[redirects]]
  from = "/screenshot/*"
  to = "/.netlify/functions/willhaben-screenshot/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
