[build]
  base = "/"
  TZ = "Europe/Berlin"

[functions]
  directory = "functions"

[functions."willhaben-database-scheduled"]
  schedule = "5/5 7 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200